name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Confirm pnpm is on PATH
        run: pnpm --version

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test
